=== jstik/services/auth/src/main/resources/jndi.config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="jndiConfig">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="type" type="xs:string"/>
                            <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="xs:string"/>
                                        <xs:element name="value" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== jstik/services/auth/src/main/resources/jndi.config.xml
<?xml version="1.0" encoding="UTF-8"?>
<jndiConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="/jndi.config.xsd">
    <resource>
        <name>jdbc/auth-ds</name>
        <type>com.zaxxer.hikari.HikariDataSource</type>
        <property>
            <name>driverClassName</name>
            <value>oracle.jdbc.driver.OracleDriver</value>
        </property>
        <property>
            <name>jdbcUrl</name>
            <value>jdbc:oracle:thin:@localhost:1521/pdborcl</value>
        </property>
        <property>
            <name>username</name>
            <value>sa</value>
        </property>
        <property>
            <name>password</name>
            <value>sa</value>
        </property>
        <property>
            <name>factory</name>
            <value>org.apache.naming.factory.BeanFactory</value>
        </property>
    </resource>
</jndiConfig>
